"""auto creative library migration 2026-08-12T20:49:49Z

Revision ID: 00c9451071a6
Revises: b731c5f09a42
Create Date: 2026-08-12 22:50:02.197604

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00c9451071a6'
down_revision = 'b731c5f09a42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('creative_library_draft_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_creative_library_draft_documents_module'))
        batch_op.create_index('ix_creative_library_draft_documents_module', ['draft_id', 'module'], unique=False)

    with op.batch_alter_table('creative_library_permission_grants', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('creative_library_permission_grants_uid_key'), type_='unique')
        batch_op.drop_index(batch_op.f('ix_creative_library_permission_grants_uid'))
        batch_op.create_index(batch_op.f('ix_creative_library_permission_grants_uid'), ['uid'], unique=True)

    with op.batch_alter_table('creative_library_product_availability', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('creative_library_product_availability_uid_key'), type_='unique')
        batch_op.drop_index(batch_op.f('ix_creative_library_product_availability_uid'))
        batch_op.create_index(batch_op.f('ix_creative_library_product_availability_uid'), ['uid'], unique=True)

    with op.batch_alter_table('creative_library_product_variants', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('creative_library_product_variants_uid_key'), type_='unique')
        batch_op.drop_index(batch_op.f('ix_creative_library_product_variants_uid'))
        batch_op.create_index(batch_op.f('ix_creative_library_product_variants_uid'), ['uid'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('creative_library_product_variants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_creative_library_product_variants_uid'))
        batch_op.create_index(batch_op.f('ix_creative_library_product_variants_uid'), ['uid'], unique=False)
        batch_op.create_unique_constraint(batch_op.f('creative_library_product_variants_uid_key'), ['uid'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('creative_library_product_availability', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_creative_library_product_availability_uid'))
        batch_op.create_index(batch_op.f('ix_creative_library_product_availability_uid'), ['uid'], unique=False)
        batch_op.create_unique_constraint(batch_op.f('creative_library_product_availability_uid_key'), ['uid'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('creative_library_permission_grants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_creative_library_permission_grants_uid'))
        batch_op.create_index(batch_op.f('ix_creative_library_permission_grants_uid'), ['uid'], unique=False)
        batch_op.create_unique_constraint(batch_op.f('creative_library_permission_grants_uid_key'), ['uid'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('creative_library_draft_documents', schema=None) as batch_op:
        batch_op.drop_index('ix_creative_library_draft_documents_module')
        batch_op.create_index(batch_op.f('ix_creative_library_draft_documents_module'), ['module'], unique=False)

    # ### end Alembic commands ###
