"""auto creative library migration 2026-06-04T12:34:27Z

Revision ID: 17092256dbc6
Revises: 
Create Date: 2026-06-04 12:34:32.693807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17092256dbc6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('creative_library_items',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('vplib_uid', sa.String(length=80), nullable=False),
    sa.Column('package_id', sa.String(length=255), nullable=True),
    sa.Column('family_id', sa.String(length=255), nullable=True),
    sa.Column('family_slug', sa.String(length=160), nullable=True),
    sa.Column('slug', sa.String(length=160), nullable=True),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('domain', sa.String(length=80), nullable=True),
    sa.Column('category', sa.String(length=120), nullable=True),
    sa.Column('subcategory', sa.String(length=120), nullable=True),
    sa.Column('classification_path', sa.String(length=512), nullable=True),
    sa.Column('taxonomy_path', sa.String(length=512), nullable=True),
    sa.Column('object_kind', sa.String(length=80), nullable=True),
    sa.Column('source_root', sa.Text(), nullable=True),
    sa.Column('source_path', sa.Text(), nullable=True),
    sa.Column('package_root', sa.Text(), nullable=True),
    sa.Column('current_revision_id', sa.BigInteger(), nullable=True),
    sa.Column('current_revision_hash', sa.String(length=128), nullable=True),
    sa.Column('latest_revision_hash', sa.String(length=128), nullable=True),
    sa.Column('published_revision_hash', sa.String(length=128), nullable=True),
    sa.Column('revision_hash', sa.String(length=128), nullable=True),
    sa.Column('default_variant_id', sa.String(length=160), nullable=True),
    sa.Column('variant_count', sa.Integer(), nullable=False),
    sa.Column('asset_count', sa.Integer(), nullable=False),
    sa.Column('document_count', sa.Integer(), nullable=False),
    sa.Column('revision_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('publication_status', sa.String(length=40), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('visible', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scanned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('summary_payload', sa.JSON(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['current_revision_id'], ['creative_library_revisions.id'], name='fk_creative_library_items_current_revision_id', ondelete='SET NULL', use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('creative_library_items', schema=None) as batch_op:
        batch_op.create_index('ix_creative_library_items_active_lookup', ['publication_status', 'enabled', 'visible', 'is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_creative_library_items_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_creative_library_items_classification_path'), ['classification_path'], unique=False)
        batch_op.create_index(batch_op.f('ix_creative_library_items_current_revision_hash'), ['current_revision_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_creative_library_items_current_revision_id'), ['current_revision_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_creative_library_items_default_variant_id'), ['default_variant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_creative_library_items_domain'), ['domain'], unique=False)
        batch_op.create_index(batch_op.f('ix_creative_library_items_enabled'), ['enabled'], unique=False)
        batch_op.create_index(batch_op.f('ix_creative_library_items_family_id'), ['family_id'], unique=False)
        batch_op.create_index('ix_creative_library_items_family_lookup', ['family_id', 'family_slug'], unique=False)
        batch_op.create_index(batch_op.f('ix_creative_library_items_family_slug'), ['family_slug'], unique=False)
        batch_op.create_index(batch_op.f('ix_creative_library_items_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index('ix_creative_library_items_kind_taxonomy', ['object_kind', 'domain', 'category'], unique=False)
        batch_op.create_index(batch_op.f('ix_creative_library_items_latest_revision_hash'), ['latest_revision_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_creative_library_items_object_kind'), ['object_kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_creative_library_items_package_id'), ['package_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_creative_library_items_publication_status'), ['publication_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_creative_library_items_published_revision_hash'), ['published_revision_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_creative_library_items_revision_hash'), ['revision_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_creative_library_items_slug'), ['slug'], unique=False)
        batch_op.create_index(batch_op.f('ix_creative_library_items_source_path'), ['source_path'], unique=False)
        batch_op.create_index('ix_creative_library_items_source_status', ['source_path', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_creative_library_items_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_creative_library_items_subcategory'), ['subcategory'], unique=False)
        batch_op.create_index('ix_creative_library_items_taxonomy', ['domain', 'category', 'subcategory'], unique=False)
        batch_op.create_index(batch_op.f('ix_creative_library_items_taxonomy_path'), ['taxonomy_path'], unique=False)
        batch_op.create_index(batch_op.f('ix_creative_library_items_visible'), ['visible'], unique=False)
        batch_op.create_index(batch_op.f('ix_creative_library_items_vplib_uid'), ['vplib_uid'], unique=True)

    op.create_table('creative_library_scan_runs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('scan_uid', sa.String(length=80), nullable=False),
    sa.Column('source_root', sa.Text(), nullable=True),
    sa.Column('mode', sa.String(length=80), nullable=True),
    sa.Column('triggered_by', sa.String(length=255), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('total_count', sa.Integer(), nullable=False),
    sa.Column('scanned_count', sa.Integer(), nullable=False),
    sa.Column('valid_count', sa.Integer(), nullable=False),
    sa.Column('invalid_count', sa.Integer(), nullable=False),
    sa.Column('created_count', sa.Integer(), nullable=False),
    sa.Column('inserted_count', sa.Integer(), nullable=False),
    sa.Column('updated_count', sa.Integer(), nullable=False),
    sa.Column('unchanged_count', sa.Integer(), nullable=False),
    sa.Column('published_count', sa.Integer(), nullable=False),
    sa.Column('skipped_count', sa.Integer(), nullable=False),
    sa.Column('deleted_count', sa.Integer(), nullable=False),
    sa.Column('duplicate_count', sa.Integer(), nullable=False),
    sa.Column('warning_count', sa.Integer(), nullable=False),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('summary_json', sa.JSON(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('creative_library_scan_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_creative_library_scan_runs_mode'), ['mode'], unique=False)
        batch_op.create_index('ix_creative_library_scan_runs_mode_status', ['mode', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_creative_library_scan_runs_scan_uid'), ['scan_uid'], unique=True)
        batch_op.create_index(batch_op.f('ix_creative_library_scan_runs_status'), ['status'], unique=False)
        batch_op.create_index('ix_creative_library_scan_runs_status_started', ['status', 'started_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_creative_library_scan_runs_triggered_by'), ['triggered_by'], unique=False)

    op.create_table('creative_library_inventory_slots',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('inventory_key', sa.String(length=120), nullable=False),
    sa.Column('slot_index', sa.Integer(), nullable=False),
    sa.Column('slot_id', sa.String(length=120), nullable=True),
    sa.Column('family_db_id', sa.BigInteger(), nullable=True),
    sa.Column('item_id', sa.BigInteger(), nullable=True),
    sa.Column('vplib_uid', sa.String(length=80), nullable=True),
    sa.Column('family_id', sa.String(length=255), nullable=True),
    sa.Column('package_id', sa.String(length=255), nullable=True),
    sa.Column('variant_id', sa.String(length=160), nullable=True),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('family_slug', sa.String(length=160), nullable=True),
    sa.Column('object_kind', sa.String(length=80), nullable=True),
    sa.Column('domain', sa.String(length=80), nullable=True),
    sa.Column('category', sa.String(length=120), nullable=True),
    sa.Column('subcategory', sa.String(length=120), nullable=True),
    sa.Column('taxonomy_path', sa.String(length=512), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('source', sa.String(length=60), nullable=True),
    sa.Column('scope', sa.String(length=60), nullable=True),
    sa.Column('mode', sa.String(length=60), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('visible', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('locked', sa.Boolean(), nullable=False),
    sa.Column('pinned', sa.Boolean(), nullable=False),
    sa.Column('selected', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('icon', sa.JSON(), nullable=False),
    sa.Column('preview', sa.JSON(), nullable=False),
    sa.Column('assets', sa.JSON(), nullable=False),
    sa.Column('variant', sa.JSON(), nullable=False),
    sa.Column('placement', sa.JSON(), nullable=False),
    sa.Column('revision_hash', sa.String(length=128), nullable=True),
    sa.Column('publication_status', sa.String(length=40), nullable=True),
    sa.Column('validation_status', sa.String(length=40), nullable=True),
    sa.Column('selected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['family_db_id'], ['creative_library_items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['item_id'], ['creative_library_items.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('inventory_key', 'slot_index', name='uq_creative_library_inventory_key_slot')
    )
    with op.batch_alter_table('creative_library_inventory_slots', schema=None) as batch_op:
        batch_op.create_index('ix_creative_library_inventory_lookup', ['inventory_key', 'enabled', 'sort_order'], unique=False)
        batch_op.create_index(batch_op.f('ix_creative_library_inventory_slots_active'), ['active'], unique=False)
        batch_op.create_index(batch_op.f('ix_creative_library_inventory_slots_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_creative_library_inventory_slots_domain'), ['domain'], unique=False)
        batch_op.create_index(batch_op.f('ix_creative_library_inventory_slots_enabled'), ['enabled'], unique=False)
        batch_op.create_index(batch_op.f('ix_creative_library_inventory_slots_family_db_id'), ['family_db_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_creative_library_inventory_slots_family_id'), ['family_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_creative_library_inventory_slots_inventory_key'), ['inventory_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_creative_library_inventory_slots_item_id'), ['item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_creative_library_inventory_slots_object_kind'), ['object_kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_creative_library_inventory_slots_package_id'), ['package_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_creative_library_inventory_slots_publication_status'), ['publication_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_creative_library_inventory_slots_revision_hash'), ['revision_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_creative_library_inventory_slots_slot_id'), ['slot_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_creative_library_inventory_slots_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_creative_library_inventory_slots_subcategory'), ['subcategory'], unique=False)
        batch_op.create_index(batch_op.f('ix_creative_library_inventory_slots_validation_status'), ['validation_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_creative_library_inventory_slots_variant_id'), ['variant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_creative_library_inventory_slots_visible'), ['visible'], unique=False)
        batch_op.create_index(batch_op.f('ix_creative_library_inventory_slots_vplib_uid'), ['vplib_uid'], unique=False)
        batch_op.create_index('ix_creative_library_inventory_taxonomy', ['domain', 'category', 'subcategory'], unique=False)
        batch_op.create_index('ix_creative_library_inventory_uid_variant', ['vplib_uid', 'variant_id'], unique=False)

    op.create_table('creative_library_revisions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('family_db_id', sa.BigInteger(), nullable=True),
    sa.Column('item_id', sa.BigInteger(), nullable=True),
    sa.Column('scan_run_id', sa.BigInteger(), nullable=True),
    sa.Column('scan_run_db_id', sa.BigInteger(), nullable=True),
    sa.Column('vplib_uid', sa.String(length=80), nullable=True),
    sa.Column('family_id', sa.String(length=255), nullable=True),
    sa.Column('package_id', sa.String(length=255), nullable=True),
    sa.Column('revision_id', sa.String(length=160), nullable=True),
    sa.Column('revision_hash', sa.String(length=128), nullable=False),
    sa.Column('previous_revision_hash', sa.String(length=128), nullable=True),
    sa.Column('package_version', sa.String(length=80), nullable=True),
    sa.Column('schema_version', sa.String(length=80), nullable=True),
    sa.Column('source_root', sa.Text(), nullable=True),
    sa.Column('source_path', sa.Text(), nullable=True),
    sa.Column('source_mtime_ns', sa.BigInteger(), nullable=True),
    sa.Column('source_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('validation_status', sa.String(length=40), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('publication_status', sa.String(length=40), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('manifest_json', sa.JSON(), nullable=False),
    sa.Column('modules_json', sa.JSON(), nullable=False),
    sa.Column('identity_json', sa.JSON(), nullable=False),
    sa.Column('classification_json', sa.JSON(), nullable=False),
    sa.Column('resolved_package_json', sa.JSON(), nullable=False),
    sa.Column('document_paths_json', sa.JSON(), nullable=False),
    sa.Column('summary_payload', sa.JSON(), nullable=False),
    sa.Column('detail_payload', sa.JSON(), nullable=False),
    sa.Column('raw_documents', sa.JSON(), nullable=False),
    sa.Column('documents', sa.JSON(), nullable=False),
    sa.Column('validation_payload', sa.JSON(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['family_db_id'], ['creative_library_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_id'], ['creative_library_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scan_run_id'], ['creative_library_scan_runs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vplib_uid', 'revision_hash', name='uq_creative_library_revision_uid_hash')
    )
    with op.batch_alter_table('creative_library_revisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_creative_library_revisions_family_db_id'), ['family_db_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_creative_library_revisions_family_id'), ['family_id'], unique=False)
        batch_op.create_index('ix_creative_library_revisions_family_status', ['family_db_id', 'publication_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_creative_library_revisions_item_id'), ['item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_creative_library_revisions_package_id'), ['package_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_creative_library_revisions_publication_status'), ['publication_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_creative_library_revisions_revision_hash'), ['revision_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_creative_library_revisions_revision_id'), ['revision_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_creative_library_revisions_scan_run_db_id'), ['scan_run_db_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_creative_library_revisions_scan_run_id'), ['scan_run_id'], unique=False)
        batch_op.create_index('ix_creative_library_revisions_scan_status', ['scan_run_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_creative_library_revisions_source_path'), ['source_path'], unique=False)
        batch_op.create_index(batch_op.f('ix_creative_library_revisions_status'), ['status'], unique=False)
        batch_op.create_index('ix_creative_library_revisions_uid_created', ['vplib_uid', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_creative_library_revisions_validation_status'), ['validation_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_creative_library_revisions_vplib_uid'), ['vplib_uid'], unique=False)

    op.create_table('creative_library_assets',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('family_db_id', sa.BigInteger(), nullable=True),
    sa.Column('item_id', sa.BigInteger(), nullable=True),
    sa.Column('revision_id', sa.BigInteger(), nullable=True),
    sa.Column('revision_db_id', sa.BigInteger(), nullable=True),
    sa.Column('vplib_uid', sa.String(length=80), nullable=True),
    sa.Column('family_id', sa.String(length=255), nullable=True),
    sa.Column('revision_hash', sa.String(length=128), nullable=True),
    sa.Column('role', sa.String(length=80), nullable=True),
    sa.Column('asset_kind', sa.String(length=80), nullable=True),
    sa.Column('asset_type', sa.String(length=80), nullable=True),
    sa.Column('asset_path', sa.Text(), nullable=True),
    sa.Column('path', sa.Text(), nullable=True),
    sa.Column('relative_path', sa.Text(), nullable=True),
    sa.Column('uri', sa.Text(), nullable=True),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('asset_hash', sa.String(length=128), nullable=True),
    sa.Column('checksum', sa.String(length=128), nullable=True),
    sa.Column('mime_type', sa.String(length=160), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('exists', sa.Boolean(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['family_db_id'], ['creative_library_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_id'], ['creative_library_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['revision_id'], ['creative_library_revisions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('creative_library_assets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_creative_library_assets_asset_hash'), ['asset_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_creative_library_assets_asset_kind'), ['asset_kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_creative_library_assets_asset_type'), ['asset_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_creative_library_assets_checksum'), ['checksum'], unique=False)
        batch_op.create_index(batch_op.f('ix_creative_library_assets_exists'), ['exists'], unique=False)
        batch_op.create_index(batch_op.f('ix_creative_library_assets_family_db_id'), ['family_db_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_creative_library_assets_family_id'), ['family_id'], unique=False)
        batch_op.create_index('ix_creative_library_assets_family_role', ['family_db_id', 'role'], unique=False)
        batch_op.create_index(batch_op.f('ix_creative_library_assets_item_id'), ['item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_creative_library_assets_revision_db_id'), ['revision_db_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_creative_library_assets_revision_hash'), ['revision_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_creative_library_assets_revision_id'), ['revision_id'], unique=False)
        batch_op.create_index('ix_creative_library_assets_revision_role', ['revision_id', 'role'], unique=False)
        batch_op.create_index(batch_op.f('ix_creative_library_assets_role'), ['role'], unique=False)
        batch_op.create_index('ix_creative_library_assets_uid_role', ['vplib_uid', 'role'], unique=False)
        batch_op.create_index(batch_op.f('ix_creative_library_assets_vplib_uid'), ['vplib_uid'], unique=False)

    op.create_table('creative_library_documents',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('family_db_id', sa.BigInteger(), nullable=True),
    sa.Column('item_id', sa.BigInteger(), nullable=True),
    sa.Column('revision_id', sa.BigInteger(), nullable=True),
    sa.Column('revision_db_id', sa.BigInteger(), nullable=True),
    sa.Column('vplib_uid', sa.String(length=80), nullable=True),
    sa.Column('family_id', sa.String(length=255), nullable=True),
    sa.Column('revision_hash', sa.String(length=128), nullable=True),
    sa.Column('relative_path', sa.Text(), nullable=False),
    sa.Column('path', sa.Text(), nullable=True),
    sa.Column('document_type', sa.String(length=80), nullable=True),
    sa.Column('module', sa.String(length=120), nullable=True),
    sa.Column('checksum', sa.String(length=128), nullable=True),
    sa.Column('document', sa.JSON(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['family_db_id'], ['creative_library_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_id'], ['creative_library_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['revision_id'], ['creative_library_revisions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('revision_id', 'relative_path', name='uq_creative_library_document_revision_path')
    )
    with op.batch_alter_table('creative_library_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_creative_library_documents_checksum'), ['checksum'], unique=False)
        batch_op.create_index(batch_op.f('ix_creative_library_documents_document_type'), ['document_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_creative_library_documents_family_db_id'), ['family_db_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_creative_library_documents_family_id'), ['family_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_creative_library_documents_item_id'), ['item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_creative_library_documents_module'), ['module'], unique=False)
        batch_op.create_index(batch_op.f('ix_creative_library_documents_revision_db_id'), ['revision_db_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_creative_library_documents_revision_hash'), ['revision_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_creative_library_documents_revision_id'), ['revision_id'], unique=False)
        batch_op.create_index('ix_creative_library_documents_revision_module', ['revision_id', 'module'], unique=False)
        batch_op.create_index('ix_creative_library_documents_uid_path', ['vplib_uid', 'relative_path'], unique=False)
        batch_op.create_index(batch_op.f('ix_creative_library_documents_vplib_uid'), ['vplib_uid'], unique=False)

    op.create_table('creative_library_scan_issues',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('scan_run_id', sa.BigInteger(), nullable=True),
    sa.Column('scan_run_db_id', sa.BigInteger(), nullable=True),
    sa.Column('family_db_id', sa.BigInteger(), nullable=True),
    sa.Column('revision_id', sa.BigInteger(), nullable=True),
    sa.Column('revision_db_id', sa.BigInteger(), nullable=True),
    sa.Column('severity', sa.String(length=40), nullable=False),
    sa.Column('level', sa.String(length=40), nullable=True),
    sa.Column('code', sa.String(length=160), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('path', sa.Text(), nullable=True),
    sa.Column('field', sa.String(length=255), nullable=True),
    sa.Column('scope', sa.String(length=120), nullable=True),
    sa.Column('source_path', sa.Text(), nullable=True),
    sa.Column('relative_path', sa.Text(), nullable=True),
    sa.Column('vplib_uid', sa.String(length=80), nullable=True),
    sa.Column('package_id', sa.String(length=255), nullable=True),
    sa.Column('family_id', sa.String(length=255), nullable=True),
    sa.Column('revision_hash', sa.String(length=128), nullable=True),
    sa.Column('context_json', sa.JSON(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['family_db_id'], ['creative_library_items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['revision_id'], ['creative_library_revisions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['scan_run_id'], ['creative_library_scan_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('creative_library_scan_issues', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_creative_library_scan_issues_code'), ['code'], unique=False)
        batch_op.create_index(batch_op.f('ix_creative_library_scan_issues_family_db_id'), ['family_db_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_creative_library_scan_issues_family_id'), ['family_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_creative_library_scan_issues_level'), ['level'], unique=False)
        batch_op.create_index(batch_op.f('ix_creative_library_scan_issues_package_id'), ['package_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_creative_library_scan_issues_revision_db_id'), ['revision_db_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_creative_library_scan_issues_revision_hash'), ['revision_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_creative_library_scan_issues_revision_id'), ['revision_id'], unique=False)
        batch_op.create_index('ix_creative_library_scan_issues_run_severity', ['scan_run_id', 'severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_creative_library_scan_issues_scan_run_db_id'), ['scan_run_db_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_creative_library_scan_issues_scan_run_id'), ['scan_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_creative_library_scan_issues_scope'), ['scope'], unique=False)
        batch_op.create_index('ix_creative_library_scan_issues_scope_severity', ['scope', 'severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_creative_library_scan_issues_severity'), ['severity'], unique=False)
        batch_op.create_index('ix_creative_library_scan_issues_uid_code', ['vplib_uid', 'code'], unique=False)
        batch_op.create_index(batch_op.f('ix_creative_library_scan_issues_vplib_uid'), ['vplib_uid'], unique=False)

    op.create_table('creative_library_variants',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('family_db_id', sa.BigInteger(), nullable=True),
    sa.Column('item_id', sa.BigInteger(), nullable=True),
    sa.Column('revision_id', sa.BigInteger(), nullable=True),
    sa.Column('revision_db_id', sa.BigInteger(), nullable=True),
    sa.Column('vplib_uid', sa.String(length=80), nullable=True),
    sa.Column('family_id', sa.String(length=255), nullable=True),
    sa.Column('revision_hash', sa.String(length=128), nullable=True),
    sa.Column('variant_id', sa.String(length=160), nullable=False),
    sa.Column('id_in_family', sa.String(length=160), nullable=True),
    sa.Column('slug', sa.String(length=160), nullable=True),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('visible', sa.Boolean(), nullable=False),
    sa.Column('family_profile_id', sa.String(length=160), nullable=True),
    sa.Column('variant_profile_id', sa.String(length=160), nullable=True),
    sa.Column('definition_values_json', sa.JSON(), nullable=False),
    sa.Column('additional_field_keys_json', sa.JSON(), nullable=False),
    sa.Column('summary_json', sa.JSON(), nullable=False),
    sa.Column('resolved_payload', sa.JSON(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('publication_status', sa.String(length=40), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['family_db_id'], ['creative_library_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_id'], ['creative_library_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['revision_id'], ['creative_library_revisions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('revision_id', 'variant_id', name='uq_creative_library_variant_revision_variant')
    )
    with op.batch_alter_table('creative_library_variants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_creative_library_variants_enabled'), ['enabled'], unique=False)
        batch_op.create_index(batch_op.f('ix_creative_library_variants_family_db_id'), ['family_db_id'], unique=False)
        batch_op.create_index('ix_creative_library_variants_family_default', ['family_db_id', 'is_default'], unique=False)
        batch_op.create_index(batch_op.f('ix_creative_library_variants_family_id'), ['family_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_creative_library_variants_family_profile_id'), ['family_profile_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_creative_library_variants_id_in_family'), ['id_in_family'], unique=False)
        batch_op.create_index(batch_op.f('ix_creative_library_variants_is_default'), ['is_default'], unique=False)
        batch_op.create_index(batch_op.f('ix_creative_library_variants_item_id'), ['item_id'], unique=False)
        batch_op.create_index('ix_creative_library_variants_profiles', ['family_profile_id', 'variant_profile_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_creative_library_variants_publication_status'), ['publication_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_creative_library_variants_revision_db_id'), ['revision_db_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_creative_library_variants_revision_hash'), ['revision_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_creative_library_variants_revision_id'), ['revision_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_creative_library_variants_slug'), ['slug'], unique=False)
        batch_op.create_index(batch_op.f('ix_creative_library_variants_status'), ['status'], unique=False)
        batch_op.create_index('ix_creative_library_variants_uid_variant', ['vplib_uid', 'variant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_creative_library_variants_variant_id'), ['variant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_creative_library_variants_variant_profile_id'), ['variant_profile_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_creative_library_variants_visible'), ['visible'], unique=False)
        batch_op.create_index(batch_op.f('ix_creative_library_variants_vplib_uid'), ['vplib_uid'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('creative_library_variants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_creative_library_variants_vplib_uid'))
        batch_op.drop_index(batch_op.f('ix_creative_library_variants_visible'))
        batch_op.drop_index(batch_op.f('ix_creative_library_variants_variant_profile_id'))
        batch_op.drop_index(batch_op.f('ix_creative_library_variants_variant_id'))
        batch_op.drop_index('ix_creative_library_variants_uid_variant')
        batch_op.drop_index(batch_op.f('ix_creative_library_variants_status'))
        batch_op.drop_index(batch_op.f('ix_creative_library_variants_slug'))
        batch_op.drop_index(batch_op.f('ix_creative_library_variants_revision_id'))
        batch_op.drop_index(batch_op.f('ix_creative_library_variants_revision_hash'))
        batch_op.drop_index(batch_op.f('ix_creative_library_variants_revision_db_id'))
        batch_op.drop_index(batch_op.f('ix_creative_library_variants_publication_status'))
        batch_op.drop_index('ix_creative_library_variants_profiles')
        batch_op.drop_index(batch_op.f('ix_creative_library_variants_item_id'))
        batch_op.drop_index(batch_op.f('ix_creative_library_variants_is_default'))
        batch_op.drop_index(batch_op.f('ix_creative_library_variants_id_in_family'))
        batch_op.drop_index(batch_op.f('ix_creative_library_variants_family_profile_id'))
        batch_op.drop_index(batch_op.f('ix_creative_library_variants_family_id'))
        batch_op.drop_index('ix_creative_library_variants_family_default')
        batch_op.drop_index(batch_op.f('ix_creative_library_variants_family_db_id'))
        batch_op.drop_index(batch_op.f('ix_creative_library_variants_enabled'))

    op.drop_table('creative_library_variants')
    with op.batch_alter_table('creative_library_scan_issues', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_creative_library_scan_issues_vplib_uid'))
        batch_op.drop_index('ix_creative_library_scan_issues_uid_code')
        batch_op.drop_index(batch_op.f('ix_creative_library_scan_issues_severity'))
        batch_op.drop_index('ix_creative_library_scan_issues_scope_severity')
        batch_op.drop_index(batch_op.f('ix_creative_library_scan_issues_scope'))
        batch_op.drop_index(batch_op.f('ix_creative_library_scan_issues_scan_run_id'))
        batch_op.drop_index(batch_op.f('ix_creative_library_scan_issues_scan_run_db_id'))
        batch_op.drop_index('ix_creative_library_scan_issues_run_severity')
        batch_op.drop_index(batch_op.f('ix_creative_library_scan_issues_revision_id'))
        batch_op.drop_index(batch_op.f('ix_creative_library_scan_issues_revision_hash'))
        batch_op.drop_index(batch_op.f('ix_creative_library_scan_issues_revision_db_id'))
        batch_op.drop_index(batch_op.f('ix_creative_library_scan_issues_package_id'))
        batch_op.drop_index(batch_op.f('ix_creative_library_scan_issues_level'))
        batch_op.drop_index(batch_op.f('ix_creative_library_scan_issues_family_id'))
        batch_op.drop_index(batch_op.f('ix_creative_library_scan_issues_family_db_id'))
        batch_op.drop_index(batch_op.f('ix_creative_library_scan_issues_code'))

    op.drop_table('creative_library_scan_issues')
    with op.batch_alter_table('creative_library_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_creative_library_documents_vplib_uid'))
        batch_op.drop_index('ix_creative_library_documents_uid_path')
        batch_op.drop_index('ix_creative_library_documents_revision_module')
        batch_op.drop_index(batch_op.f('ix_creative_library_documents_revision_id'))
        batch_op.drop_index(batch_op.f('ix_creative_library_documents_revision_hash'))
        batch_op.drop_index(batch_op.f('ix_creative_library_documents_revision_db_id'))
        batch_op.drop_index(batch_op.f('ix_creative_library_documents_module'))
        batch_op.drop_index(batch_op.f('ix_creative_library_documents_item_id'))
        batch_op.drop_index(batch_op.f('ix_creative_library_documents_family_id'))
        batch_op.drop_index(batch_op.f('ix_creative_library_documents_family_db_id'))
        batch_op.drop_index(batch_op.f('ix_creative_library_documents_document_type'))
        batch_op.drop_index(batch_op.f('ix_creative_library_documents_checksum'))

    op.drop_table('creative_library_documents')
    with op.batch_alter_table('creative_library_assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_creative_library_assets_vplib_uid'))
        batch_op.drop_index('ix_creative_library_assets_uid_role')
        batch_op.drop_index(batch_op.f('ix_creative_library_assets_role'))
        batch_op.drop_index('ix_creative_library_assets_revision_role')
        batch_op.drop_index(batch_op.f('ix_creative_library_assets_revision_id'))
        batch_op.drop_index(batch_op.f('ix_creative_library_assets_revision_hash'))
        batch_op.drop_index(batch_op.f('ix_creative_library_assets_revision_db_id'))
        batch_op.drop_index(batch_op.f('ix_creative_library_assets_item_id'))
        batch_op.drop_index('ix_creative_library_assets_family_role')
        batch_op.drop_index(batch_op.f('ix_creative_library_assets_family_id'))
        batch_op.drop_index(batch_op.f('ix_creative_library_assets_family_db_id'))
        batch_op.drop_index(batch_op.f('ix_creative_library_assets_exists'))
        batch_op.drop_index(batch_op.f('ix_creative_library_assets_checksum'))
        batch_op.drop_index(batch_op.f('ix_creative_library_assets_asset_type'))
        batch_op.drop_index(batch_op.f('ix_creative_library_assets_asset_kind'))
        batch_op.drop_index(batch_op.f('ix_creative_library_assets_asset_hash'))

    op.drop_table('creative_library_assets')
    with op.batch_alter_table('creative_library_revisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_creative_library_revisions_vplib_uid'))
        batch_op.drop_index(batch_op.f('ix_creative_library_revisions_validation_status'))
        batch_op.drop_index('ix_creative_library_revisions_uid_created')
        batch_op.drop_index(batch_op.f('ix_creative_library_revisions_status'))
        batch_op.drop_index(batch_op.f('ix_creative_library_revisions_source_path'))
        batch_op.drop_index('ix_creative_library_revisions_scan_status')
        batch_op.drop_index(batch_op.f('ix_creative_library_revisions_scan_run_id'))
        batch_op.drop_index(batch_op.f('ix_creative_library_revisions_scan_run_db_id'))
        batch_op.drop_index(batch_op.f('ix_creative_library_revisions_revision_id'))
        batch_op.drop_index(batch_op.f('ix_creative_library_revisions_revision_hash'))
        batch_op.drop_index(batch_op.f('ix_creative_library_revisions_publication_status'))
        batch_op.drop_index(batch_op.f('ix_creative_library_revisions_package_id'))
        batch_op.drop_index(batch_op.f('ix_creative_library_revisions_item_id'))
        batch_op.drop_index('ix_creative_library_revisions_family_status')
        batch_op.drop_index(batch_op.f('ix_creative_library_revisions_family_id'))
        batch_op.drop_index(batch_op.f('ix_creative_library_revisions_family_db_id'))

    op.drop_table('creative_library_revisions')
    with op.batch_alter_table('creative_library_inventory_slots', schema=None) as batch_op:
        batch_op.drop_index('ix_creative_library_inventory_uid_variant')
        batch_op.drop_index('ix_creative_library_inventory_taxonomy')
        batch_op.drop_index(batch_op.f('ix_creative_library_inventory_slots_vplib_uid'))
        batch_op.drop_index(batch_op.f('ix_creative_library_inventory_slots_visible'))
        batch_op.drop_index(batch_op.f('ix_creative_library_inventory_slots_variant_id'))
        batch_op.drop_index(batch_op.f('ix_creative_library_inventory_slots_validation_status'))
        batch_op.drop_index(batch_op.f('ix_creative_library_inventory_slots_subcategory'))
        batch_op.drop_index(batch_op.f('ix_creative_library_inventory_slots_status'))
        batch_op.drop_index(batch_op.f('ix_creative_library_inventory_slots_slot_id'))
        batch_op.drop_index(batch_op.f('ix_creative_library_inventory_slots_revision_hash'))
        batch_op.drop_index(batch_op.f('ix_creative_library_inventory_slots_publication_status'))
        batch_op.drop_index(batch_op.f('ix_creative_library_inventory_slots_package_id'))
        batch_op.drop_index(batch_op.f('ix_creative_library_inventory_slots_object_kind'))
        batch_op.drop_index(batch_op.f('ix_creative_library_inventory_slots_item_id'))
        batch_op.drop_index(batch_op.f('ix_creative_library_inventory_slots_inventory_key'))
        batch_op.drop_index(batch_op.f('ix_creative_library_inventory_slots_family_id'))
        batch_op.drop_index(batch_op.f('ix_creative_library_inventory_slots_family_db_id'))
        batch_op.drop_index(batch_op.f('ix_creative_library_inventory_slots_enabled'))
        batch_op.drop_index(batch_op.f('ix_creative_library_inventory_slots_domain'))
        batch_op.drop_index(batch_op.f('ix_creative_library_inventory_slots_category'))
        batch_op.drop_index(batch_op.f('ix_creative_library_inventory_slots_active'))
        batch_op.drop_index('ix_creative_library_inventory_lookup')

    op.drop_table('creative_library_inventory_slots')
    with op.batch_alter_table('creative_library_scan_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_creative_library_scan_runs_triggered_by'))
        batch_op.drop_index('ix_creative_library_scan_runs_status_started')
        batch_op.drop_index(batch_op.f('ix_creative_library_scan_runs_status'))
        batch_op.drop_index(batch_op.f('ix_creative_library_scan_runs_scan_uid'))
        batch_op.drop_index('ix_creative_library_scan_runs_mode_status')
        batch_op.drop_index(batch_op.f('ix_creative_library_scan_runs_mode'))

    op.drop_table('creative_library_scan_runs')
    with op.batch_alter_table('creative_library_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_creative_library_items_vplib_uid'))
        batch_op.drop_index(batch_op.f('ix_creative_library_items_visible'))
        batch_op.drop_index(batch_op.f('ix_creative_library_items_taxonomy_path'))
        batch_op.drop_index('ix_creative_library_items_taxonomy')
        batch_op.drop_index(batch_op.f('ix_creative_library_items_subcategory'))
        batch_op.drop_index(batch_op.f('ix_creative_library_items_status'))
        batch_op.drop_index('ix_creative_library_items_source_status')
        batch_op.drop_index(batch_op.f('ix_creative_library_items_source_path'))
        batch_op.drop_index(batch_op.f('ix_creative_library_items_slug'))
        batch_op.drop_index(batch_op.f('ix_creative_library_items_revision_hash'))
        batch_op.drop_index(batch_op.f('ix_creative_library_items_published_revision_hash'))
        batch_op.drop_index(batch_op.f('ix_creative_library_items_publication_status'))
        batch_op.drop_index(batch_op.f('ix_creative_library_items_package_id'))
        batch_op.drop_index(batch_op.f('ix_creative_library_items_object_kind'))
        batch_op.drop_index(batch_op.f('ix_creative_library_items_latest_revision_hash'))
        batch_op.drop_index('ix_creative_library_items_kind_taxonomy')
        batch_op.drop_index(batch_op.f('ix_creative_library_items_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_creative_library_items_family_slug'))
        batch_op.drop_index('ix_creative_library_items_family_lookup')
        batch_op.drop_index(batch_op.f('ix_creative_library_items_family_id'))
        batch_op.drop_index(batch_op.f('ix_creative_library_items_enabled'))
        batch_op.drop_index(batch_op.f('ix_creative_library_items_domain'))
        batch_op.drop_index(batch_op.f('ix_creative_library_items_default_variant_id'))
        batch_op.drop_index(batch_op.f('ix_creative_library_items_current_revision_id'))
        batch_op.drop_index(batch_op.f('ix_creative_library_items_current_revision_hash'))
        batch_op.drop_index(batch_op.f('ix_creative_library_items_classification_path'))
        batch_op.drop_index(batch_op.f('ix_creative_library_items_category'))
        batch_op.drop_index('ix_creative_library_items_active_lookup')

    op.drop_table('creative_library_items')
    # ### end Alembic commands ###
