"""auto creative library migration 2026-07-02T16:43:48Z

Revision ID: 231dff38cb8e
Revises: e78c68374b96
Create Date: 2026-07-02 18:43:56.914796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '231dff38cb8e'
down_revision = 'e78c68374b96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('creative_library_draft_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_creative_library_draft_documents_status'))
        batch_op.create_index('ix_creative_library_draft_documents_status', ['draft_id', 'status', 'active'], unique=False)

    with op.batch_alter_table('creative_library_draft_variants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_creative_library_draft_variants_status'))
        batch_op.create_index(batch_op.f('ix_creative_library_draft_variants_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('creative_library_draft_variants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_creative_library_draft_variants_status'))
        batch_op.create_index(batch_op.f('ix_creative_library_draft_variants_status'), ['draft_id', 'status', 'active'], unique=False)

    with op.batch_alter_table('creative_library_draft_documents', schema=None) as batch_op:
        batch_op.drop_index('ix_creative_library_draft_documents_status')
        batch_op.create_index(batch_op.f('ix_creative_library_draft_documents_status'), ['status'], unique=False)

    # ### end Alembic commands ###
