"""auto creative library migration 2026-06-04T12:48:23Z

Revision ID: 27da70134b68
Revises: 17092256dbc6
Create Date: 2026-06-04 12:48:29.850890

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27da70134b68'
down_revision = '17092256dbc6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('creative_library_items', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_creative_library_items_current_revision_id', 'creative_library_revisions', ['current_revision_id'], ['id'], ondelete='SET NULL', use_alter=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('creative_library_items', schema=None) as batch_op:
        batch_op.drop_constraint('fk_creative_library_items_current_revision_id', type_='foreignkey')

    # ### end Alembic commands ###
