"""auto creative library migration 2026-06-29T20:04:46Z

Revision ID: 3d55ef0845a7
Revises: 6b66b7c9eaf2
Create Date: 2026-06-29 22:04:53.702531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d55ef0845a7'
down_revision = '6b66b7c9eaf2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('creative_library_draft_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_creative_library_draft_documents_module'))
        batch_op.create_index('ix_creative_library_draft_documents_module', ['draft_id', 'module'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('creative_library_draft_documents', schema=None) as batch_op:
        batch_op.drop_index('ix_creative_library_draft_documents_module')
        batch_op.create_index(batch_op.f('ix_creative_library_draft_documents_module'), ['module'], unique=False)

    # ### end Alembic commands ###
