"""auto creative library migration 2026-06-28T17:52:44Z

Revision ID: 503ce72556ba
Revises: 5fb951f575c1
Create Date: 2026-06-28 19:52:52.647176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '503ce72556ba'
down_revision = '5fb951f575c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('creative_library_draft_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_creative_library_draft_documents_module'))
        batch_op.create_index(batch_op.f('ix_creative_library_draft_documents_module'), ['module'], unique=False)
        batch_op.drop_index(batch_op.f('ix_creative_library_draft_documents_status'))
        batch_op.create_index('ix_creative_library_draft_documents_status', ['draft_id', 'status', 'active'], unique=False)

    with op.batch_alter_table('creative_library_draft_variants', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_creative_library_draft_variants_source_variant_id', 'creative_library_variants', ['source_variant_id'], ['id'], ondelete='SET NULL', use_alter=True)

    with op.batch_alter_table('creative_library_drafts', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_creative_library_drafts_target_item_id', 'creative_library_items', ['target_item_id'], ['id'], ondelete='SET NULL', use_alter=True)
        batch_op.create_foreign_key('fk_creative_library_drafts_published_revision_id', 'creative_library_revisions', ['published_revision_id'], ['id'], ondelete='SET NULL', use_alter=True)
        batch_op.create_foreign_key('fk_creative_library_drafts_base_revision_id', 'creative_library_revisions', ['base_revision_id'], ['id'], ondelete='SET NULL', use_alter=True)

    with op.batch_alter_table('creative_library_items', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_creative_library_items_current_revision_id', 'creative_library_revisions', ['current_revision_id'], ['id'], ondelete='SET NULL', use_alter=True)

    with op.batch_alter_table('creative_library_revisions', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_creative_library_revisions_source_draft_id', 'creative_library_drafts', ['source_draft_id'], ['id'], ondelete='SET NULL', use_alter=True)

    with op.batch_alter_table('creative_library_variants', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_creative_library_variants_source_draft_variant_id', 'creative_library_draft_variants', ['source_draft_variant_id'], ['id'], ondelete='SET NULL', use_alter=True)

    with op.batch_alter_table('library_files', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_library_files_current_version_id', 'library_file_versions', ['current_version_id'], ['id'], ondelete='SET NULL', use_alter=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('library_files', schema=None) as batch_op:
        batch_op.drop_constraint('fk_library_files_current_version_id', type_='foreignkey')

    with op.batch_alter_table('creative_library_variants', schema=None) as batch_op:
        batch_op.drop_constraint('fk_creative_library_variants_source_draft_variant_id', type_='foreignkey')

    with op.batch_alter_table('creative_library_revisions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_creative_library_revisions_source_draft_id', type_='foreignkey')

    with op.batch_alter_table('creative_library_items', schema=None) as batch_op:
        batch_op.drop_constraint('fk_creative_library_items_current_revision_id', type_='foreignkey')

    with op.batch_alter_table('creative_library_drafts', schema=None) as batch_op:
        batch_op.drop_constraint('fk_creative_library_drafts_base_revision_id', type_='foreignkey')
        batch_op.drop_constraint('fk_creative_library_drafts_published_revision_id', type_='foreignkey')
        batch_op.drop_constraint('fk_creative_library_drafts_target_item_id', type_='foreignkey')

    with op.batch_alter_table('creative_library_draft_variants', schema=None) as batch_op:
        batch_op.drop_constraint('fk_creative_library_draft_variants_source_variant_id', type_='foreignkey')

    with op.batch_alter_table('creative_library_draft_documents', schema=None) as batch_op:
        batch_op.drop_index('ix_creative_library_draft_documents_status')
        batch_op.create_index(batch_op.f('ix_creative_library_draft_documents_status'), ['status'], unique=False)
        batch_op.drop_index(batch_op.f('ix_creative_library_draft_documents_module'))
        batch_op.create_index(batch_op.f('ix_creative_library_draft_documents_module'), ['draft_id', 'module'], unique=False)

    # ### end Alembic commands ###
