"""auto creative library migration 2026-08-02T09:17:41Z

Revision ID: 5b418100171f
Revises: 3613bbe1dee2
Create Date: 2026-08-02 11:17:55.498568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b418100171f'
down_revision = '3613bbe1dee2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('library_definition_profile_bindings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_library_definition_profile_bindings_priority'))
        batch_op.create_index(batch_op.f('ix_library_definition_profile_bindings_priority'), ['priority'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('library_definition_profile_bindings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_library_definition_profile_bindings_priority'))
        batch_op.create_index(batch_op.f('ix_library_definition_profile_bindings_priority'), ['priority', 'active'], unique=False)

    # ### end Alembic commands ###
