"""auto creative library migration 2026-07-24T12:24:44Z

Revision ID: 64f35632cd06
Revises: 3b6fd621ccba
Create Date: 2026-07-24 14:24:58.554511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64f35632cd06'
down_revision = '3b6fd621ccba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('creative_library_draft_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_creative_library_draft_documents_module'))
        batch_op.create_index(batch_op.f('ix_creative_library_draft_documents_module'), ['module'], unique=False)
        batch_op.drop_index(batch_op.f('ix_creative_library_draft_documents_status'))
        batch_op.create_index(batch_op.f('ix_creative_library_draft_documents_status'), ['status'], unique=False)

    with op.batch_alter_table('library_definition_profile_bindings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_library_definition_profile_bindings_priority'))
        batch_op.create_index('ix_library_definition_profile_bindings_priority', ['priority', 'active'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('library_definition_profile_bindings', schema=None) as batch_op:
        batch_op.drop_index('ix_library_definition_profile_bindings_priority')
        batch_op.create_index(batch_op.f('ix_library_definition_profile_bindings_priority'), ['priority'], unique=False)

    with op.batch_alter_table('creative_library_draft_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_creative_library_draft_documents_status'))
        batch_op.create_index(batch_op.f('ix_creative_library_draft_documents_status'), ['draft_id', 'status', 'active'], unique=False)
        batch_op.drop_index(batch_op.f('ix_creative_library_draft_documents_module'))
        batch_op.create_index(batch_op.f('ix_creative_library_draft_documents_module'), ['draft_id', 'module'], unique=False)

    # ### end Alembic commands ###
