"""auto creative library migration 2026-08-08T16:05:49Z

Revision ID: 68c484df618d
Revises: 686e45bf347c
Create Date: 2026-08-08 18:06:05.493660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68c484df618d'
down_revision = '686e45bf347c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('library_definition_profile_bindings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_library_definition_profile_bindings_priority'))
        batch_op.create_index(batch_op.f('ix_library_definition_profile_bindings_priority'), ['priority'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('library_definition_profile_bindings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_library_definition_profile_bindings_priority'))
        batch_op.create_index(batch_op.f('ix_library_definition_profile_bindings_priority'), ['priority', 'active'], unique=False)

    # ### end Alembic commands ###
