"""auto creative library migration 2026-08-07T13:41:58Z

Revision ID: 6c10f94ab93a
Revises: 6cfcde875627
Create Date: 2026-08-07 15:42:14.131972

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c10f94ab93a'
down_revision = '6cfcde875627'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('library_definition_profile_bindings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_library_definition_profile_bindings_priority'))
        batch_op.create_index(batch_op.f('ix_library_definition_profile_bindings_priority'), ['priority'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('library_definition_profile_bindings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_library_definition_profile_bindings_priority'))
        batch_op.create_index(batch_op.f('ix_library_definition_profile_bindings_priority'), ['priority', 'active'], unique=False)

    # ### end Alembic commands ###
