"""auto creative library migration 2026-08-01T11:27:49Z

Revision ID: 81bbb0aeeae1
Revises: 7f8cf1264c36
Create Date: 2026-08-01 13:28:09.730483

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81bbb0aeeae1'
down_revision = '7f8cf1264c36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('library_definition_profile_bindings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_library_definition_profile_bindings_priority'))
        batch_op.create_index(batch_op.f('ix_library_definition_profile_bindings_priority'), ['priority'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('library_definition_profile_bindings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_library_definition_profile_bindings_priority'))
        batch_op.create_index(batch_op.f('ix_library_definition_profile_bindings_priority'), ['priority', 'active'], unique=False)

    # ### end Alembic commands ###
