"""auto creative library migration 2026-08-01T13:36:53Z

Revision ID: 8bfaefad46ba
Revises: d8623af79ee6
Create Date: 2026-08-01 15:37:05.882119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bfaefad46ba'
down_revision = 'd8623af79ee6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('creative_library_draft_variants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_creative_library_draft_variants_status'))
        batch_op.create_index('ix_creative_library_draft_variants_status', ['draft_id', 'status', 'active'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('creative_library_draft_variants', schema=None) as batch_op:
        batch_op.drop_index('ix_creative_library_draft_variants_status')
        batch_op.create_index(batch_op.f('ix_creative_library_draft_variants_status'), ['status'], unique=False)

    # ### end Alembic commands ###
