"""auto creative library migration 2026-07-10T19:34:23Z

Revision ID: 9e2eeb437323
Revises: bd408c8fa0ae
Create Date: 2026-07-10 21:34:38.596945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e2eeb437323'
down_revision = 'bd408c8fa0ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('creative_library_draft_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_creative_library_draft_documents_module'))
        batch_op.create_index(batch_op.f('ix_creative_library_draft_documents_module'), ['module'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('creative_library_draft_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_creative_library_draft_documents_module'))
        batch_op.create_index(batch_op.f('ix_creative_library_draft_documents_module'), ['draft_id', 'module'], unique=False)

    # ### end Alembic commands ###
