"""auto creative library migration 2026-08-03T22:06:26Z

Revision ID: 9fe3ce4fce9a
Revises: 8d317c1403b6
Create Date: 2026-08-04 00:06:44.451318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fe3ce4fce9a'
down_revision = '8d317c1403b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('creative_library_draft_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_creative_library_draft_documents_module'))
        batch_op.create_index('ix_creative_library_draft_documents_module', ['draft_id', 'module'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('creative_library_draft_documents', schema=None) as batch_op:
        batch_op.drop_index('ix_creative_library_draft_documents_module')
        batch_op.create_index(batch_op.f('ix_creative_library_draft_documents_module'), ['module'], unique=False)

    # ### end Alembic commands ###
