"""auto creative library migration 2026-07-10T19:05:49Z

Revision ID: ade7f5137447
Revises: 3415ee0d6db4
Create Date: 2026-07-10 21:06:04.046251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ade7f5137447'
down_revision = '3415ee0d6db4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('creative_library_draft_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_creative_library_draft_documents_status'))
        batch_op.create_index('ix_creative_library_draft_documents_status', ['draft_id', 'status', 'active'], unique=False)

    with op.batch_alter_table('creative_library_draft_variants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_creative_library_draft_variants_status'))
        batch_op.create_index('ix_creative_library_draft_variants_status', ['draft_id', 'status', 'active'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('creative_library_draft_variants', schema=None) as batch_op:
        batch_op.drop_index('ix_creative_library_draft_variants_status')
        batch_op.create_index(batch_op.f('ix_creative_library_draft_variants_status'), ['status'], unique=False)

    with op.batch_alter_table('creative_library_draft_documents', schema=None) as batch_op:
        batch_op.drop_index('ix_creative_library_draft_documents_status')
        batch_op.create_index(batch_op.f('ix_creative_library_draft_documents_status'), ['status'], unique=False)

    # ### end Alembic commands ###
