"""auto creative library migration 2026-06-26T20:45:15Z

Revision ID: bbb37dceab4a
Revises: 27da70134b68
Create Date: 2026-06-26 22:45:21.813012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbb37dceab4a'
down_revision = '27da70134b68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_inventory_states',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('inventory_key', sa.String(length=120), nullable=False),
    sa.Column('active_slot_index', sa.Integer(), nullable=False),
    sa.Column('last_selected_slot_index', sa.Integer(), nullable=False),
    sa.Column('last_selected_slot_key', sa.String(length=120), nullable=False),
    sa.Column('last_selected_item_db_id', sa.BigInteger(), nullable=True),
    sa.Column('last_selected_vplib_uid', sa.String(length=80), nullable=True),
    sa.Column('last_selected_family_id', sa.String(length=255), nullable=True),
    sa.Column('last_selected_package_id', sa.String(length=255), nullable=True),
    sa.Column('last_selected_variant_id', sa.String(length=160), nullable=True),
    sa.Column('last_selected_label', sa.String(length=255), nullable=True),
    sa.Column('last_selected_object_kind', sa.String(length=80), nullable=True),
    sa.Column('last_selected_domain', sa.String(length=80), nullable=True),
    sa.Column('last_selected_category', sa.String(length=120), nullable=True),
    sa.Column('last_selected_subcategory', sa.String(length=120), nullable=True),
    sa.Column('last_selected_taxonomy_path', sa.String(length=512), nullable=True),
    sa.Column('slot_count', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=60), nullable=False),
    sa.Column('scope', sa.String(length=60), nullable=False),
    sa.Column('mode', sa.String(length=60), nullable=False),
    sa.Column('selected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_loaded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('settings', sa.JSON(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('active_slot_index >= 1 AND active_slot_index <= 9', name='ck_user_inventory_state_active_slot_range'),
    sa.CheckConstraint('last_selected_slot_index >= 1 AND last_selected_slot_index <= 9', name='ck_user_inventory_state_last_slot_range'),
    sa.CheckConstraint('slot_count = 9', name='ck_user_inventory_state_slot_count'),
    sa.ForeignKeyConstraint(['last_selected_item_db_id'], ['creative_library_items.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'inventory_key', name='uq_user_inventory_state_user_inventory')
    )
    with op.batch_alter_table('user_inventory_states', schema=None) as batch_op:
        batch_op.create_index('ix_user_inventory_state_last_item', ['last_selected_vplib_uid', 'last_selected_variant_id'], unique=False)
        batch_op.create_index('ix_user_inventory_state_selection', ['user_id', 'inventory_key', 'active_slot_index'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_inventory_states_inventory_key'), ['inventory_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_inventory_states_last_selected_category'), ['last_selected_category'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_inventory_states_last_selected_domain'), ['last_selected_domain'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_inventory_states_last_selected_family_id'), ['last_selected_family_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_inventory_states_last_selected_item_db_id'), ['last_selected_item_db_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_inventory_states_last_selected_object_kind'), ['last_selected_object_kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_inventory_states_last_selected_package_id'), ['last_selected_package_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_inventory_states_last_selected_subcategory'), ['last_selected_subcategory'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_inventory_states_last_selected_variant_id'), ['last_selected_variant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_inventory_states_last_selected_vplib_uid'), ['last_selected_vplib_uid'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_inventory_states_user_id'), ['user_id'], unique=False)

    op.create_table('user_inventory_slots',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('state_id', sa.BigInteger(), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('inventory_key', sa.String(length=120), nullable=False),
    sa.Column('slot_index', sa.Integer(), nullable=False),
    sa.Column('slot_key', sa.String(length=120), nullable=False),
    sa.Column('item_db_id', sa.BigInteger(), nullable=True),
    sa.Column('vplib_uid', sa.String(length=80), nullable=True),
    sa.Column('family_id', sa.String(length=255), nullable=True),
    sa.Column('package_id', sa.String(length=255), nullable=True),
    sa.Column('variant_id', sa.String(length=160), nullable=True),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('object_kind', sa.String(length=80), nullable=True),
    sa.Column('domain', sa.String(length=80), nullable=True),
    sa.Column('category', sa.String(length=120), nullable=True),
    sa.Column('subcategory', sa.String(length=120), nullable=True),
    sa.Column('taxonomy_path', sa.String(length=512), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('empty', sa.Boolean(), nullable=False),
    sa.Column('selected', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('locked', sa.Boolean(), nullable=False),
    sa.Column('pinned', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=60), nullable=False),
    sa.Column('scope', sa.String(length=60), nullable=False),
    sa.Column('mode', sa.String(length=60), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('icon', sa.JSON(), nullable=False),
    sa.Column('preview', sa.JSON(), nullable=False),
    sa.Column('assets', sa.JSON(), nullable=False),
    sa.Column('variant', sa.JSON(), nullable=False),
    sa.Column('placement', sa.JSON(), nullable=False),
    sa.Column('selected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cleared_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('quantity >= 0', name='ck_user_inventory_slot_quantity_non_negative'),
    sa.CheckConstraint('slot_index >= 1 AND slot_index <= 9', name='ck_user_inventory_slot_index_range'),
    sa.ForeignKeyConstraint(['item_db_id'], ['creative_library_items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['state_id'], ['user_inventory_states.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'inventory_key', 'slot_index', name='uq_user_inventory_slot_user_inventory_index'),
    sa.UniqueConstraint('user_id', 'inventory_key', 'slot_key', name='uq_user_inventory_slot_user_inventory_key')
    )
    with op.batch_alter_table('user_inventory_slots', schema=None) as batch_op:
        batch_op.create_index('ix_user_inventory_slot_item_uid_variant', ['vplib_uid', 'variant_id'], unique=False)
        batch_op.create_index('ix_user_inventory_slot_lookup', ['user_id', 'inventory_key', 'slot_index'], unique=False)
        batch_op.create_index('ix_user_inventory_slot_selection', ['user_id', 'inventory_key', 'selected'], unique=False)
        batch_op.create_index('ix_user_inventory_slot_taxonomy', ['domain', 'category', 'subcategory'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_inventory_slots_active'), ['active'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_inventory_slots_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_inventory_slots_domain'), ['domain'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_inventory_slots_empty'), ['empty'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_inventory_slots_family_id'), ['family_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_inventory_slots_inventory_key'), ['inventory_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_inventory_slots_item_db_id'), ['item_db_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_inventory_slots_object_kind'), ['object_kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_inventory_slots_package_id'), ['package_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_inventory_slots_selected'), ['selected'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_inventory_slots_slot_key'), ['slot_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_inventory_slots_state_id'), ['state_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_inventory_slots_subcategory'), ['subcategory'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_inventory_slots_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_inventory_slots_variant_id'), ['variant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_inventory_slots_vplib_uid'), ['vplib_uid'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_inventory_slots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_inventory_slots_vplib_uid'))
        batch_op.drop_index(batch_op.f('ix_user_inventory_slots_variant_id'))
        batch_op.drop_index(batch_op.f('ix_user_inventory_slots_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_inventory_slots_subcategory'))
        batch_op.drop_index(batch_op.f('ix_user_inventory_slots_state_id'))
        batch_op.drop_index(batch_op.f('ix_user_inventory_slots_slot_key'))
        batch_op.drop_index(batch_op.f('ix_user_inventory_slots_selected'))
        batch_op.drop_index(batch_op.f('ix_user_inventory_slots_package_id'))
        batch_op.drop_index(batch_op.f('ix_user_inventory_slots_object_kind'))
        batch_op.drop_index(batch_op.f('ix_user_inventory_slots_item_db_id'))
        batch_op.drop_index(batch_op.f('ix_user_inventory_slots_inventory_key'))
        batch_op.drop_index(batch_op.f('ix_user_inventory_slots_family_id'))
        batch_op.drop_index(batch_op.f('ix_user_inventory_slots_empty'))
        batch_op.drop_index(batch_op.f('ix_user_inventory_slots_domain'))
        batch_op.drop_index(batch_op.f('ix_user_inventory_slots_category'))
        batch_op.drop_index(batch_op.f('ix_user_inventory_slots_active'))
        batch_op.drop_index('ix_user_inventory_slot_taxonomy')
        batch_op.drop_index('ix_user_inventory_slot_selection')
        batch_op.drop_index('ix_user_inventory_slot_lookup')
        batch_op.drop_index('ix_user_inventory_slot_item_uid_variant')

    op.drop_table('user_inventory_slots')
    with op.batch_alter_table('user_inventory_states', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_inventory_states_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_inventory_states_last_selected_vplib_uid'))
        batch_op.drop_index(batch_op.f('ix_user_inventory_states_last_selected_variant_id'))
        batch_op.drop_index(batch_op.f('ix_user_inventory_states_last_selected_subcategory'))
        batch_op.drop_index(batch_op.f('ix_user_inventory_states_last_selected_package_id'))
        batch_op.drop_index(batch_op.f('ix_user_inventory_states_last_selected_object_kind'))
        batch_op.drop_index(batch_op.f('ix_user_inventory_states_last_selected_item_db_id'))
        batch_op.drop_index(batch_op.f('ix_user_inventory_states_last_selected_family_id'))
        batch_op.drop_index(batch_op.f('ix_user_inventory_states_last_selected_domain'))
        batch_op.drop_index(batch_op.f('ix_user_inventory_states_last_selected_category'))
        batch_op.drop_index(batch_op.f('ix_user_inventory_states_inventory_key'))
        batch_op.drop_index('ix_user_inventory_state_selection')
        batch_op.drop_index('ix_user_inventory_state_last_item')

    op.drop_table('user_inventory_states')
    # ### end Alembic commands ###
