"""auto creative library migration 2026-07-28T16:27:39Z

Revision ID: bceb46c8a6a0
Revises: 186c3c3611dd
Create Date: 2026-07-28 18:27:52.951623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bceb46c8a6a0'
down_revision = '186c3c3611dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('creative_library_draft_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_creative_library_draft_documents_module'))
        batch_op.create_index('ix_creative_library_draft_documents_module', ['draft_id', 'module'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('creative_library_draft_documents', schema=None) as batch_op:
        batch_op.drop_index('ix_creative_library_draft_documents_module')
        batch_op.create_index(batch_op.f('ix_creative_library_draft_documents_module'), ['module'], unique=False)

    # ### end Alembic commands ###
