"""auto creative library migration 2026-09-01T06:16:04Z

Revision ID: c9fc165aa21c
Revises: 597260c17168
Create Date: 2026-09-01 08:16:16.577206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9fc165aa21c'
down_revision = '597260c17168'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('library_definition_profile_bindings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_library_definition_profile_bindings_priority'))
        batch_op.create_index('ix_library_definition_profile_bindings_priority', ['priority', 'active'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('library_definition_profile_bindings', schema=None) as batch_op:
        batch_op.drop_index('ix_library_definition_profile_bindings_priority')
        batch_op.create_index(batch_op.f('ix_library_definition_profile_bindings_priority'), ['priority'], unique=False)

    # ### end Alembic commands ###
