"""auto creative library migration 2026-08-15T13:44:58Z

Revision ID: d14ed0c03b09
Revises: b6dca772d577
Create Date: 2026-08-15 15:45:20.073404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd14ed0c03b09'
down_revision = 'b6dca772d577'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('creative_library_draft_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_creative_library_draft_documents_module'))
        batch_op.create_index('ix_creative_library_draft_documents_module', ['draft_id', 'module'], unique=False)
        batch_op.drop_index(batch_op.f('ix_creative_library_draft_documents_status'))
        batch_op.create_index(batch_op.f('ix_creative_library_draft_documents_status'), ['status'], unique=False)

    with op.batch_alter_table('creative_library_draft_variants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_creative_library_draft_variants_status'))
        batch_op.create_index('ix_creative_library_draft_variants_status', ['draft_id', 'status', 'active'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('creative_library_draft_variants', schema=None) as batch_op:
        batch_op.drop_index('ix_creative_library_draft_variants_status')
        batch_op.create_index(batch_op.f('ix_creative_library_draft_variants_status'), ['status'], unique=False)

    with op.batch_alter_table('creative_library_draft_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_creative_library_draft_documents_status'))
        batch_op.create_index(batch_op.f('ix_creative_library_draft_documents_status'), ['draft_id', 'status', 'active'], unique=False)
        batch_op.drop_index('ix_creative_library_draft_documents_module')
        batch_op.create_index(batch_op.f('ix_creative_library_draft_documents_module'), ['module'], unique=False)

    # ### end Alembic commands ###
