"""auto creative library migration 2026-07-10T16:05:36Z

Revision ID: e0e4c5a86d68
Revises: 9e619d050a9b
Create Date: 2026-07-10 18:05:51.883099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0e4c5a86d68'
down_revision = '9e619d050a9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('creative_library_draft_variants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_creative_library_draft_variants_status'))
        batch_op.create_index(batch_op.f('ix_creative_library_draft_variants_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('creative_library_draft_variants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_creative_library_draft_variants_status'))
        batch_op.create_index(batch_op.f('ix_creative_library_draft_variants_status'), ['draft_id', 'status', 'active'], unique=False)

    # ### end Alembic commands ###
