"""auto creative library migration 2026-08-09T13:29:12Z

Revision ID: e4a4293ee920
Revises: 3e803ea2963a
Create Date: 2026-08-09 15:29:27.541488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4a4293ee920'
down_revision = '3e803ea2963a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('creative_library_draft_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_creative_library_draft_documents_status'))
        batch_op.create_index('ix_creative_library_draft_documents_status', ['draft_id', 'status', 'active'], unique=False)

    with op.batch_alter_table('library_definition_profile_bindings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_library_definition_profile_bindings_priority'))
        batch_op.create_index('ix_library_definition_profile_bindings_priority', ['priority', 'active'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('library_definition_profile_bindings', schema=None) as batch_op:
        batch_op.drop_index('ix_library_definition_profile_bindings_priority')
        batch_op.create_index(batch_op.f('ix_library_definition_profile_bindings_priority'), ['priority'], unique=False)

    with op.batch_alter_table('creative_library_draft_documents', schema=None) as batch_op:
        batch_op.drop_index('ix_creative_library_draft_documents_status')
        batch_op.create_index(batch_op.f('ix_creative_library_draft_documents_status'), ['status'], unique=False)

    # ### end Alembic commands ###
